---
title: "datetime plotting"
author: "Jilung Hsieh"
date: "2020/10/12"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
options(stringsAsFactors = F)
```

# Loading data
```{r}
ptturl <- "https://github.com/P4CSS/R4CSSData/raw/main/ptt_hang_posts.csv"
raw <- read.csv(url(ptturl))
clean <- raw %>%
        mutate(ptime = as.POSIXct(strptime(ptime, "%Y-%m-%dT%H:%M:%SZ", tz = "ASIA/Taipeiw")))

raw <- read_csv(url(ptturl))
?read_csv

```


# parsing time
- Convert "character time"  to R date.time object (POSIXct)
```{r}
t <- "2019-04-12T00:48:19Z"
class(t)
?strptime
t1 <- strptime(t, "%Y-%m-%dT%H:%M:%SZ")
raw %>% 
     %>% glimpse()
    
```


# Data coverage over time
```{r}
raw %>%
    ggplot() + aes(ptime) + 
    geom_density()
    
```


# Data coverage over time by month
```{r}
?lubridate
raw %>%
    mutate(m = month(ptime)) %>% 
    count(m) %>%
    ggplot() + aes(m, n) + 
    geom_col()
    

```

```{r}
raw %>%
    filter(ptime >= as_date("2019-03-18") & ptime < as_date("2019-04-01")) %>%
    mutate(m = floor_date(ptime, unit = "day")) %>% 
    count(m) %>%
    ggplot() + aes(m, n) + 
    geom_col()
```



# Data coverage overt time by hour, grouped by day
```{r}
clean %>%
    filter(ptime >= as_date("2019-03-25") & ptime < as_date("2019-04-01")) %>%
    mutate(d = floor_date(ptime, unit = "day")) %>%
    mutate(h = hour(ptime)) %>%
    count(d, h) %>%
    mutate(wd = wday(d, label = F, locale = Sys.getlocale("LC_TIME"))) %>% View
    mutate(isweekend = ifelse(wd >= 6, "weekend", "weekday")) %>%
    ggplot() + aes(h, n, color = as.character(d)) + 
    geom_line() + 
    facet_wrap(~isweekend)

?ifelse
```





