```{r include=FALSE}
knitr::opts_chunk$set(cache = T, warning = F, message = FALSE, class.output = "output")
```

# Introduction {#introduction}

本書旨在為新聞傳播領域的研究生與專業記者提供一部實用指南，介紹如何運用 R 語言進行數據分析與視覺化，進而產出具有深度與說服力的數據驅動新聞報導。全書內容由淺入深，初步以 R 語言的基礎語法（base R）入門，幫助讀者了解 R 語言最初為統計分析而設計的初衷，並掌握數據操作與統計建模的核心知識。打好這一堅實基礎後，讀者將能更深入地理解並應用後續進階工具。

隨著數據科學在各行各業中迅速發展，`tidyverse` 生態系統以其直觀的語法和高效的數據處理流程已成為現代數據分析的主流。本書後半部將重點介紹 `tidyverse` 主要函式庫，如 `dplyr`、`ggplot2` 與 `tidyr`，協助讀者熟悉這些工具，並能夠靈活應用於實際新聞報導製作中。透過本書，讀者不僅能夠學習 R 語言的基本與進階技能，還能夠將數據轉化為具有新聞價值的故事與視覺呈現。

### **書中數據集**

本書所使用的各項資料皆可從 GitHub [R4CSS/data](https://github.com/p4css/R4CSS/tree/master/data) 下載，這些數據涵蓋了多元的新聞議題，旨在提供讀者真實且豐富的練習素材。

### **案例介紹**

書中精心挑選了多個實例，以展示如何應用 R 語言處理與視覺化不同類型的新聞數據，案例包括但不限於：

-   **Paid Maternity Leave over 197 Countries**：以條形圖呈現各國帶薪產假的情況

-   **Taipei Residential Hot Spot**：利用列聯表分析台北住宅熱點與類別數據

-   **Trump's Tweets**：結合折線圖、條形圖、時間軸以及文字處理技術解析特朗普推文

-   **NYT: Net Worth by Age Group**：透過折線圖展示不同年齡層的淨資產趨勢

-   **NYT: Carbon Proportion**：採用樹狀圖展示碳排放比例

-   **NYT: Optimism by Countries**：分析各國民眾的樂觀程度

-   **NYT: Population Growth**：呈現人口增長趨勢

-   **Annual Budget of TW Government**：通過 NA 處理與樹狀圖解析台灣政府年度預算

-   **Vaccinating Proportion by Country x Year**：展示各國不同年度的疫苗接種比例

-   **NYT: LeBron James's Achievement**：呈現 LeBron James 的成就數據

透過上述案例，讀者將學會如何從原始數據出發，經由清理、轉換、分析，再到最終的圖表視覺化，將複雜的數據故事轉化為直觀易懂的新聞內容。這不僅能提升讀者在數據分析方面的專業能力，更能培養其將數據應用於實際新聞製作的創意思維。
