---
title: "R03_1_base_to_dplyr_maternal_leave"
author: "Jilung Hsieh"
date: "3/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading library

```{r}
library(tidyverse)
library(readxl)
library(dplyr)
library(tidyr)
library(ggplot2)

options(stringsAsFactors = F)
```

## Loading data

```{r}

raw <- read_excel("data/WORLD-MACHE_Gender_6.8.15.xls", "Sheet1", col_names=T)
```

## Select and filter data

```{r}
matleave <- select(raw, iso3, 6:24)
m5 <- filter(matleave, matleave_13==5)
m55 <- filter(m5, matleave_95==5)
```

## Using pipeline

```{r}
m55 <- read_excel("data/WORLD-MACHE_Gender_6.8.15.xls", "Sheet1", col_names=T) %>%
    select(iso3, 6:24) %>%
    filter(matleave_13==5) %>%
    filter(matleave_95==5)
```

## Pure dplyr

```{r}
library(dplyr)
library(tidyr)
library(ggplot2)
library(readxl)

read_excel("data/WORLD-MACHE_Gender_6.8.15.xls", "Sheet1", col_names=T) %>%
	select(iso3, contains("matleave"), -contains("wrr")) %>%
	filter(matleave_13==5, matleave_95!=5) %>%
	gather("year", "degree", 2:20) %>%
	replace_na(list(degree=0)) %>%
	mutate(year2=as.POSIXct(strptime(year, "matleave_%y"))) %>%
	mutate(year3 = strftime(year2, "%Y")) %>%
	ggplot() +
	aes(year3, degree) +
    geom_col(color="royalblue", fill="royalblue") + 
	facet_wrap(~ iso3) + 
    theme_void()
```
