---
title: "R04_1_join_twdemo_ref"
author: "Jilung Hsieh"
date: "2020/4/18"
output:
  html_document:
    theme: cerulean
    highlight: zenburn
    toc: yes
    toc_float:
      collapsed: no
    df_print: paged
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# install.packages("tidyverse")
library(tidyverse)
options(stringsAsFactors = F)
options(verbose = T)
options(scipen = 999)
```

# Read demographic data: read csv
```{r read csv}
raw <- read_csv("data/opendata107Y030.csv") %>%
    slice(-1) %>%
    mutate(vname = str_c(site_id, village)) %>%
    select(vname, everything())

raw %>% 
    mutate_at(vars(6:157), as.numeric) %>%
    replace(is.na(.), 0) %>%
    rowwise() %>% 
    mutate(married = sum(c_across(matches("widowed|divorced|married")), na.rm = T)) %>%
  mutate(lt65 = sum(c_across(matches("65|70|75|80|85|90|95|100")), na.rm = T)) %>%
    select(vname, married, lt65) %>% View

raw %>% glimpse()
```

# Tidy data
```{r}
tidy_data <- raw %>%
    gather("key", "value", 6:ncol(.)) %>% 
    mutate(key = str_replace(key, "_age", "")) %>%
    mutate(key = str_replace(key, "100up", "100_110")) %>%
    mutate(key = str_replace(key, "15down", "0_15")) %>%
    separate(key, c("married", "ageLower", "ageUpper", "gender")) %>%
    mutate(ageLower = as.numeric(ageLower),
           # age = str(ageLower, ageUpper), 
           ageUpper = as.numeric(ageUpper),
           value = as.numeric(value)) %>%
    select(-statistic_yyy) %>%
    arrange(vname)
    
```

# Summarized by villages

```{r}

village_stat <- tidy_data %>%
    filter(ageLower >= 20) %>%
    group_by(vname) %>%
    summarise(legalPopulation = sum(value),
              elderSum = sum(value[ageLower >= 65]),
              marriedSum = sum(value[married %in% c("married", "divorced", "widowed")]),
              womenSum = sum(value[gender == "f"])) %>%
    ungroup() %>%
    left_join(raw %>% select(vname, site_id), by = "vname")
    
```


# Merging original data fields

```{r}
village_stat %>%
  mutate(townname = str_sub(vname, 1, 6)) %>%
  filter(site_id != townname) %>% View


village_stat %>%
  separate(vname, c("townname", "villagename"), sep = "鄉|鎮|市|區", remove = F) %>%
  filter(site_id != townname) %>% View

village_stat %>%
    left_join(raw %>% select(vname, site_id), by = "vname") %>% head()
```



# Aggregating to town level stat

```{r}
town_stat <- village_stat %>%
    # mutate(site_id = str_sub(vname, 1, 6)) %>%
    mutate(site_id = str_replace(site_id, "三民一|三民二", "三民區")) %>%
    mutate(site_id = str_replace(site_id, "鳳山一|鳳山二", "鳳山區")) %>%
    group_by(site_id) %>%
    summarize(legalPopulation =  sum(legalPopulation),
              elderSum = sum(elderSum),
              marriedSum = sum(marriedSum),
              womenSum = sum(womenSum)
              )%>%
    ungroup()
```


# Visualizing to explore
```{r}
town_stat %>%
    mutate(marriedPerc = marriedSum / legalPopulation) %>%
    mutate(womenPerc = womenSum / legalPopulation) %>%
    mutate(elderPerc = elderSum / legalPopulation) %>% 
    ggplot() +
    aes(marriedPerc, elderPerc) + 
    geom_jitter(alpha = 0.3)
```




# Loading referendum data

```{r}
ref10 <- read_csv("data/referendum_byTown/ref10.csv") %>%
    select(county = 縣市, town = 鄉鎮市區,
            agree = 同意票數, disagree = 不同意票數,
           legalVote = 有效票數, illegalVote = 無效票數, 
           vote = 投票數, legalPopulation =  投票權人數)  %>%
    mutate(site_id = str_c(county, town)) %>%
    drop_na(site_id)

names(ref10)
```


# try to join data
```{r}
town_stat %>% left_join(ref10, by = "site_id") %>% View
```


# Joining demographic and referendum data
```{r}
town_stat %>%
    mutate(site_id = str_replace(site_id, "東　區", "東區"),
           site_id = str_replace(site_id, "西　區", "西區"),
           site_id = str_replace(site_id, "南　區", "南區"),
           site_id = str_replace(site_id, "北　區", "北區"),
           site_id = str_replace(site_id, "中　區", "中區")) %>%
    left_join(ref10, by = "site_id") %>%
    mutate(agreeRate = agree / legalVote,
           marriedPerc = marriedSum / legalPopulation.x) %>%
    select(site_id, agree, legalVote, marriedSum, legalPopulation.x) %>% View
    ggplot() + 
    aes(agreeRate, marriedPerc) + 
    geom_jitter(alpha = 0.5, color = "royalblue") + 
    theme_light()
```




