---
title: "R04_5 ggplotly"
author: "Jilung Hsieh"
date: "`r Sys.Date()`"
output: html_document
---

```{r echo=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
options(scipen = 999)

th <- theme_minimal() + 
  theme(
    title = element_text(family="Heiti TC Light"), #all title elements
    text = element_text(family="Heiti TC Light"),  #all text elements
    plot.title = element_text(face="bold"),
    axis.title.x = element_text(hjust=1, face="bold.italic"),
    axis.title.y = element_text(hjust=1, face="bold.italic"),
        )

```

# ggplotly

[Scatter plots with ggplot2 (plotly.com)](https://plotly.com/ggplot2/line-and-scatter/)

```{r include=FALSE}

# install.packages("plotly")
library(plotly)
```

# LINE CHART

[Line plots with R (plotly.com)](https://plotly.com/r/line-charts/)

## Basic

事實上要產生互動式的圖表非常簡單。除了在一開始要載入`plotly`套件外，只需要把`ggplot()`的結果指給一個變項（如下方的`NW.plot`，然後用`ggplotly(NW.plot)`繪圖即可。多加一個`config(displayModeBar = FALSE)`是為了不要顯示`plotly`的控制列。

```{r}
NW <- read_csv("data/interactive_bulletin_charts_agecl_median.csv") %>%
    select(Category, year, Net_Worth)  %>%
    group_by(Category) %>%
    arrange(year) %>%
    ungroup()

NW.plot <- NW %>%    
    ggplot() + 
    aes(year, Net_Worth, color=Category) + 
    geom_line() + 
    theme_minimal() + 
    labs(title = "Net Worth by year grouped by age groups",
         x = "Year",
         y = "Net Worth") + th

ggplotly(NW.plot)
  config(displayModeBar = FALSE)
```

可以在`aes()`設定要帶入圖的變數時，新增一個`text`變數，手動設定要呈現的動態呈現方塊。但要注意的是，要多加入一個`group=1`才能夠作用（WHY？）

```{r cleaning-ggplot1, message=FALSE, warning=FALSE, include=FALSE}
NW <- read_csv("data/interactive_bulletin_charts_agecl_median.csv") %>%
    select(Category, year, Net_Worth)  %>%
    group_by(Category) %>%
    arrange(year) %>%
    ungroup()

NW.plot <- NW %>%    
    ggplot() + 
    aes(year, Net_Worth, 
        color=Category, 
        text = paste0("<b>年(X): </b>", year, "<br>",
                      "<b>淨資產(Y): </b>", Net_Worth,"<br>",
                      "<b>年齡組: </b>", Category),
        group=Category) + 
    geom_line() + 
    theme_minimal() + 
    labs(title = "Net Worth by year grouped by age groups",
         x = "Year",
         y = "Net Worth") + th

ggplotly(NW.plot, tooltip = "text") %>%
  config(displayModeBar = FALSE)
```

# SCATTER

```{r cleaning2, message=FALSE, warning=FALSE, include=FALSE}
bw <- read_csv("data/unicef-changing-childhood-data.csv") %>% 
    select(country = WP5, age = WP22140, bw = WP22092) %>%
    mutate(country = ordered(country, 
                             levels=c(1, 3, 4, 10, 11, 12, 13, 14, 17, 
                                      29, 31, 33, 35, 36, 60, 61, 77, 
                                      79, 81, 87, 165), 
                             labels=c("USA", "Morocco", "Lebanon",
                                      "Indonesia","Bangladesh", "UK", 
                                      "France", "Germany", "Spain", 
                                      "Japan", "India", "Brazil", 
                                      "Nigeria", "Kenya", "Ethiopia",
                                      "Mali", "Ukraine", "Cameroon", 
                                      "Zimbabwe","Argentina", "Peru"))) %>%
    count(country, age, bw) %>%
    group_by(country, age) %>%
    mutate(perc = n/sum(n)) %>% 
    ungroup() %>%
    filter(bw == 1) %>%
    select(country, age, perc) %>%
    spread(age, perc) %>%
    rename(`15-24y` = `1`, `40+y` = `2`)
```

```{r  ggplot2, message=FALSE, warning=FALSE, include=FALSE}
bw.p <- bw %>%
    ggplot() + aes(`40+y`, `15-24y`, label = country) + 
    geom_point(color = "skyblue", size = 2) + 
    xlim(0.2, 0.85) + ylim(0.2, 0.85) + 
    geom_text(hjust = -0.1, vjust = -0.5) + 
    geom_abline(intercept = 0, slop = 1, 
                color="lightgrey", alpha=0.5, linetype="dashed") + 
    th + 
    theme(aspect.ratio=1)
```

```{r ggplotly2, message=FALSE, warning=FALSE}
bw.p %>% ggplotly()
```

# Barplot

[Bar charts with R (plotly.com)](https://plotly.com/r/bar-charts/)

```{r cleaning-ggplot3, message=FALSE, warning=FALSE, include=FALSE}
county <- read_csv("data/tw_population_opendata110N010.csv") %>%
    slice(-1, -(370:375)) %>%
    type_convert() %>%
    mutate(county = str_sub(site_id, 1, 3)) %>%
    group_by(county) %>%
    summarize(
        area = sum(area), 
        people_total = sum(people_total)
    ) %>%
    ungroup()

population.p <- county %>%
  mutate(county = reorder(county, people_total)) %>%
  ggplot() + aes(county, people_total) %>%
  geom_col(fill="skyblue") +
  coord_flip() + th
```

```{r ggplotly3}
population.p %>% ggplotly()
```

# Boxplot

[Box plots with ggplot2 (plotly.com)](https://plotly.com/ggplot2/box-plots/)

```{r cleaning-ggplot4, message=FALSE, warning=FALSE, include=FALSE}
aqi.toplot <- read_rds("https://github.com/p4css/R4CSS/raw/master/data/AQI_Chaozhou.rds") %>%
    arrange(日期)%>%
    filter(測項=="PM2.5") %>%
    gather("hour", "PM25", 4:28) %>%
    mutate(PM25 = as.numeric(PM25)) %>%
    drop_na() %>%
    mutate(year = lubridate::year(日期), month = lubridate::month(日期)) %>%
    filter(month %in% c(11, 12, 1, 2, 3))

aqi.plot <- aqi.toplot %>%
    mutate(year = as.character(year)) %>%
    ggplot() + aes(x=year, y=PM25)  + 
    geom_boxplot(fill="skyblue", alpha=0.2) + 
    ylim(0, 200) + 
    coord_flip() + 
    theme_minimal()
```

```{r ggplotly4, message=FALSE, warning=FALSE}
aqi.plot %>% ggplotly
```

# Treemap (Global Cabrbon)

```{r cleaning5, message=FALSE, warning=FALSE, include=FALSE}
totreemap <- read_csv("data/GCB2021v34_MtCO2_flat.csv") %>% 
    drop_na(`Total`) %>%
    filter(!Country %in% c("Global", "International Transport")) %>%
    filter(Year==2020) %>%
    arrange(desc(`Total`)) %>%
    mutate(perc = Total/sum(Total)) %>%
    slice(1:20)
library(treemapify)
totreemap %>%
    ggplot() + aes(area = perc, fill=`Per Capita`, label=Country) +
    geom_treemap() + 
    geom_treemap_text(color="white", 
                      place="centre", 
                      grow=TRUE
                      )
```

```{r fail-ggplotly}
carbon.p %>% ggplotly
```
